version: '3'

services:
  zoo1:
    image: zookeeper:3.4
    hostname: zoo1
    container_name: zoo1
    ports:
    - 2182:2181
    volumes:
    - "D:\\MyAppData\\volume\\zkcluster\\zoo1\\data:/data"
    - "D:\\MyAppData\\volume\\zkcluster\\zoo1\\datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      xionDev:
        ipv4_address: 172.16.1.11

  zoo2:
    image: zookeeper:3.4
    hostname: zoo2
    container_name: zoo2
    ports:
    - 2183:2181
    volumes:
    - "D:\\MyAppData\\volume\\zkcluster\\zoo2\\data:/data"
    - "D:\\MyAppData\\volume\\zkcluster\\zoo2\\datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      xionDev:
        ipv4_address: 172.16.1.12

  zoo3:
    image: zookeeper:3.4
    hostname: zoo3
    container_name: zoo3
    ports:
    - 2184:2181
    volumes:
    - "D:\\MyAppData\\volume\\zkcluster\\zoo3\\data:/data"
    - "D:\\MyAppData\\volume\\zkcluster\\zoo3\\datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      xionDev:
        ipv4_address: 172.16.1.13

networks:
  xionDev:
    external: true